### ISSUE TITLE
Make AssertJ 2.x and 3.x work as a dependency

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#90] opened 2016-07-22 07:37 UTC
We are currently on assertJ 1.7.1 (Oct. 2014). The latest release release is 3.5.1 (July 2016). 

(3.5.1 should be more then twice as good, because versions! ;))

**Comment by jangalinski** [comment] 2016-07-22 07:44
1.7.0 is the last version that still works with java6 ... so unless we are willing to go to java8, assert-j 3.x is out of reach

**Comment by martinschimak** [comment] 2016-07-23 07:47
While AssertJ is the only dependency pulled in when using camunda-bpm-assert, the user can change to use a different version of course. AssertJ 1.x is for Java6, 2.x for Java7 and 3.x for Java8, as @jangalinski already indicates. But when using camunda-bpm-assert with JDK 7 or 8, it would actually be nice to be able to use a 2.x or 3.x version of AssertJ. If somebody has the time to sort that out, please move forward: 

* Question 1: does camunda-bpm-assert work with AssertJ 2.x Java 7/8 and AssertJ 3.x (Java 8)?
* Question 2: if not, is it feasible and what would be needed to enable that?

(I am on vacation for the next two weeks btw... will answer to anything popping up after that ...)

**Comment by jangalinski** [comment] 2016-07-24 09:26
Answer 1: we are using camunda-bpm-assert 2.0-alpha1 with java 8 and assertj-core 3.5.1 and so far did encounter any problems.

**Comment by berndruecker** [comment] 2017-08-03 11:11
There is a reproducable problem with asserj-core 2.x or 3.x:
```
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/util/Map;)Lorg/assertj/core/api/AbstractMapAssert;
	at org.camunda.bpm.engine.test.assertions.bpmn.ProcessInstanceAssert.variables(ProcessInstanceAssert.java:581)
```

or 
```
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/util/List;)Lorg/assertj/core/api/AbstractListAssert;
```

I can simply reproduce it by changing seeting a dependency in this project https://github.com/camunda/camunda-bpm-assert/tree/master/camunda-bpm-assert-bpmn-examples

```
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>2.6.0</version>
		</dependency>
```

**Comment by berndruecker** [comment] 2017-11-21 12:38
See https://app.camunda.com/jira/browse/CAM-8296

**Comment by jangalinski** [comment] 2017-11-21 20:58
I solved this with the camunda-spring-boot-test module by adding the camunda-bpm-assert sources to the module and recompile it with Java8 and assert-j 2.

**Comment by stefanbecke** [comment] 2017-11-29 08:45
In our project @kuehne+nagel we want to use the latest assertj-core version 3.8.0, but this camunda.bpm.extension still requires an old assertj-core version (1.7.1). 

Please provide a new official version of this extension which uses the latest assertj-core version. Other projects, which are **not** using Java 8 can still stick to the _“old”_ version, but projects, which are using Java 8 have a general requirement to keep their 3rd-party libraries up-to-date (so as we). 

Beside of this, I would recommend that further assertions for camunda services as for DMN are getting supported.

BTW: If this extension needs some support to provide this update, we @kuehne+nagel would like to support (as a sponsor).

**Comment by jangalinski** [comment] 2017-12-11 12:59
workaround: Something like this: https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/starter-test/pom.xml works, so you copy the sources and compile with java8/assertj 3.x and use your local build instead of the maven-central one. Of course you must not use both at the same time!

**Comment by martinschimak** [comment] 2018-01-12 16:44
Hi all. I want to close this (bit nasty) issue, which is kind of a prerequisite to move on with some other suggestions and pull requests and release all that as 2.0... therefore

I'd appreciate some real life feedback on PR #109

The build now creates three artifacts, compiled for Java 6, 7 and 8. After having built the pull request locally, you could use the library in some test project of yours...

```xml
<dependency>
    <groupId>org.camunda.bpm.extension</groupId>
    <artifactId>camunda-bpm-assert-java8</artifactId>
    <version>2.0-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
```

You should then see that AssertJ 3.9.0 is pulled in transitively, for Java 7 AssertJ 2.9.0 is used and Java 6 relies on 1.7.1. As the compilation is now done against the correct AssertJ 2.x/3.x version you can of course also use another minor version of those libraries then the one pulled in. 

And maybe @jangalinski can even try whether this smoothly works with the spring boot starter project. Would be awesome...

**Comment by jangalinski** [comment] 2018-01-12 17:19
Hi Martin, thanks for picking this up. This is the least invasive solution which still allows all the backward compatibility. I will test this and also check/enhance the spring-boot test.

Great!
Jan

**Comment by stefanzilske** [comment] 2018-06-05 15:42
@martinschimak 

any news on this? It seems that with camunda-spring-boot-starter-test:3.0.0 the workaround by @jangalinski, to include recompiled sources based on a newer AssertJ version, has been removed.

Also, it would be nice to finally have 2.0 release instead of using an alpha version, which always carries the risk that APIs might change...

Cheers,
Stefan

**Comment by malteser** [comment] 2018-06-18 16:14
Is this extension dead?

**Comment by martinschimak** [comment] 2018-06-18 16:38
From my perspective, it's not. This was just a nasty issue that blocked us for a too long time. And I  sorted it out btw. When you read a bit above, I think @jangalinski wanted to test this and also check/enhance the spring-boot test. In my PR #109, also linked in my comment above, you can see that he wanted to check if this pull request is really usable under real life conditions with the spring boot extension. It did not happen however. I do not *expect* this to happen btw, just as we all should not *expect* from each other to contribute. Free work can just happen in spare time. So I guess a few people's spare time is down to zero since a while. Fair enough.

**Comment by jangalinski** [comment] 2018-06-19 09:43
Hi .. I was not aware that this is waiting for my feedback, sorry. I did a test a while back and it seemed to work, Problem is, that I am mostly behind enterprise proxies, so its difficult for me to test under real-life conditions with a snapshot.
I would vote for releasing an alpha that we then can evaluate via maven-central and afterwards go for a final release.
Publish early - publish often

**Comment by StephenOTT** [comment] 2018-06-21 18:40
+1 on geting fixes

**Comment by justinwyer** [comment] 2018-06-28 07:31
Anything I can do to help get PR #109 merged and an alpha3 with java 8 support released, I'll make the time to get this done over the next week. Showing a team how nice it is to write tests for Camunda isn't so easy when you're forced to do all the boilerplate low level `RuntimeService`, `TaskService`, `...Service` interaction.

**Comment by g-zimmer** [comment] 2018-07-13 12:06
+1 for this fix! In our customer project, we also would like to use newer versions of AssertJ without having to rely on alpha versions.

**Comment by placsta** [comment] 2018-07-24 14:32
+1 for the fix, too.
I currently upgrade from camunda-bpm-spring-boot-starter-test 2.3.0 to 3.0.0 (camunda 7.8 to 7.9). The old starter shipped with assert and used assertJ 2.6.0. The new SpringBoot test starter (2.0.2.RELEASE) uses 3.9.1. We don't want to downgrade to 1.7.1, because we alot of the new assertJ features.

**Comment by falko** [comment] 2018-08-29 05:48
The Camunda Spring Boot Maven Archetype is affected by this issue as well. What is the status of the fix?

**Comment by martinschimak** [comment] 2018-08-29 09:47
Hi all, really sorry for me being unresponsive these days. I am going through times, which are on one hand just great *and* on the other hand also very challenging. As much as I still love my little baby project here (it was my first public pet project), I would also love to experience it growing up and being maintained by Camunda. :-) Having said that... in the week of CamundaCon (I will hang around) there will be some time on my side to look into this: 1) check whether everything with this fix still works, because it's already old again, and then 2) merge it and 3) get it published. Thank you for your patience.

**Comment by martinschimak** [comment] 2018-09-24 08:16
Last week I've been speaking with four different and very smart people at CamundaCon. I wanted to get feedback to the following question: does it really make sense to release this fix NOW ... considering that it will result in different artifacts for all Java versions still in use out there AND considering the plans several Camunda people vent with regards to this extension? The answer by all four of them was: no it does not make sense. So I am currently patiently waiting for a decision.

**Comment by StephenOTT** [comment] 2018-09-24 14:07
>considering the plans several Camunda people vent with regards to this extension? 

Can you detail some more on this?

**Comment by berndruecker** [comment] 2018-10-04 10:34
Hey guys. Let me quickly jump in to fill the gaps: We decided to move the camunda-bpm-assert extensions into the core product scope - as it is so valuable that almost every customer uses it. So we do want to provide the typical Camunda EE guarantees and make sure the library is actively maintained (for Martin it is still a hobby to do that - so huge kudos that he kept up so far anyway!). 
But we couldn't make it for upcoming 7.10 because of reasons ;-) Reasons being quite a lot of work to do and other priorities. So it will be 7.11 in May 2019. With that move the maven coordinates will change anyway - so it makes most sense to also address this issue when doing this. That is what Martin meant. So the ball is on our (Camunda) side and we plan to address soon after 7.10 is done. 
Cheers
Bernd

**Comment by timguy** [comment] 2018-10-26 07:58
@martinschimak Thanks so far for maintaining. Is it possible to release a last version to maven-central including the PR #109? Maybe as version 3.0-alpha1?
This would help to close the gap until May 2019 when it's planned to release 7.11.

(Same what jangalinski already suggested)
> 
> I would vote for releasing an alpha that we then can evaluate via maven-central and afterwards go for a final release.
> Publish early - publish often

**Comment by tmetzke** [comment] 2019-03-19 15:19
Hey guys,

thanks for being patient with this and sorry for the time it took to finally get this done.
As @berndruecker already mentioned, we were in the process of moving the extension into the core product scope but couldn't fit this into 7.10.

As of release 3.0.0-alpha1, the extension now is an official part of Camunda BPM.
Huge thanks to @martinschimak from my side here as well for working on this with us and maintaining the extension up until now. The final release of the 3.0.0 is scheduled for May 2019.

We decided to provide different artifacts for different AssertJ versions and further explain on this in our [blog post](https://blog.camunda.com/post/2019/03/camunda-bpm-assert-300-alpha1-released/). The maven coordinates slightly changed as well, as Bernd already stated.

If you have any feedback on this, please don't hesitate to share.

We are closing this as fixed and will reopen if there are any problems with this.

Best,
Tobias

**Closed by tmetzke** 2019-03-19 15:19 UTC
Labels: fix (bug)
